import { FundingStage } from './FundingStage';
import { TheirStackShortJobDTO } from './ShortJobDTO';

export type TheirStackCompanyDTO = {
  id: string;
  name?: string;
  domain?: string;
  industry?: string;
  country?: string;
  country_code?: string;
  employee_count?: number;
  logo?: string;
  num_jobs?: number;
  num_technologies?: number;
  possible_domains?: string[];
  url?: string;
  industry_id?: number;
  linkedin_url?: string;
  num_jobs_last_30_days?: number;
  num_jobs_found?: number;
  yc_batch?: string;
  apollo_id?: string;
  linkedin_id?: string;
  url_source?: string;
  is_recruiting_agency?: boolean;
  founded_year?: number;
  annual_revenue_usd?: number;
  annual_revenue_usd_readable?: string;
  total_funding_usd?: number;
  last_funding_round_date?: string;
  last_funding_round_amount_readable?: string;
  employee_count_range?: string;
  long_description?: string;
  seo_description?: string;
  city?: string;
  postal_code?: string;
  company_keywords?: string[];
  alexa_ranking?: number;
  publicly_traded_symbol?: string;
  publicly_traded_exchange?: string;
  investors?: string[];
  funding_stage?: FundingStage;
  has_blurred_data?: boolean;
  technology_slugs?: string[];
  technology_names?: string[];
  technologies_found?: Array<{
    technology: {
      name: string;
      category?: string;
      slug?: string;
      category_slug?: string;
      parent_category?: string;
      parent_category_slug?: string;
      logo?: string;
      logo_thumbnail?: string;
    };
    confidence?: 'low' | 'medium' | 'high';
    jobs?: number;
    jobs_last_7_days?: number;
    jobs_last_30_days?: number;
    jobs_last_180_days?: number;
    first_date_found?: string;
    last_date_found?: string;
    rank_within_category?: number;
    relative_occurrence_within_category?: number;
    theirstack_score?: number;
    company_name?: string;
  }>;
  jobs_found?: Array<TheirStackShortJobDTO>;
}
